name: Run Full Automation

on:
  workflow_dispatch: {}  

# GITHUB_TOKEN can stay read-only; PAT will do the pushing
permissions:
  contents: read

jobs:
  run-automation:
    runs-on: axep-ubuntu-latest-medium

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # needed for proper git history when committing

      - name: Show repository root (diagnostic)
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies if present
        run: |
          if [ -f Full_automation/requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r Full_automation/requirements.txt
          else
            echo "No requirements.txt found; skipping pip install."
          fi

      - name: Run automation and create log file
        shell: bash
        run: |
          set -euo pipefail

          cd Full_automation

          if [ ! -f command.txt ]; then
            echo "❌ ERROR: command.txt missing" >&2
            exit 1
          fi

          CMD=$(cat command.txt)

          # Extract DAG name from command: supports "--dag value" or "--dag=value"
          DAG_NAME=""
          if [[ "$CMD" =~ --dag[=[:space:]]*([^[:space:]]+) ]]; then
            DAG_NAME="${BASH_REMATCH[1]}"
          else
            DAG_NAME="unknown_dag"
          fi

          # Ensure Logs directory exists
          mkdir -p Logs

          # Build timestamped log file name
          TS=$(date +%Y%m%d_%H%M%S)
          LOGFILE="Logs/${DAG_NAME}_${TS}.txt"

          echo "▶ Running command: $CMD"
          echo "▶ Logging to: $(pwd)/$LOGFILE"

          # Run the command; capture stdout+stderr to the log and show in Actions logs
          bash -lc "$CMD" 2>&1 | tee "$LOGFILE"

          echo "-------------------------------------"
          echo "Log created at: $(pwd)/$LOGFILE"
          echo "-------------------------------------"

      - name: Commit log back to repo using PAT
        env:
          PAT_TOKEN: ${{ secrets.REPO_PAT }}
        shell: bash
        run: |
          set -euo pipefail

          # Basic git identity for the commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage any new/updated log files
          git add Full_automation/Logs/*.txt || echo "No log files to add"

          # If nothing staged, exit gracefully
          if git diff --cached --quiet; then
            echo "No new log files to commit."
            exit 0
          fi

          # Create commit
          git commit -m "Add DAG logs on $(date '+%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"

          # Configure 'origin' to use PAT securely (do NOT echo this URL)
          # GITHUB_SERVER_URL example: https://github.com
          # GITHUB_REPOSITORY example: org-name/repo-name
          git remote set-url origin "https://x-access-token:${PAT_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git"

          # Push to current branch
          git push origin HEAD
